name: 'coverage'
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: macos-latest
        if: ${{ github.actor != 'dependabot' }}
        steps:
            - name: Check user
              run: echo ${{ github.actor}}
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2.2.4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  annotations: coverage
